server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # If the request is /something, but /something.html exists,
  # serve it transparently.
  location / {
    try_files $uri $uri/ $uri.html $uri/index.html =404;
  }
}
