http:
  routers:
    site:
      rule: "Host(`backslashfox.ch`)"
      entryPoints:
        - websecure
      tls:
        certResolver: le
      service: site-svc

    site-http:
      rule: "Host(`backslashfox.ch`)"
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: site-svc

  services:
    site-svc:
      loadBalancer:
        servers:
          - url: "http://web:80"

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
